# Generated by Django 4.2.11 on 2026-05-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
