# Generated by Django 4.2.11 on 2026-05-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_guiderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('trainer', 'Trainer'), ('member', 'Member')], db_index=True, default='member', max_length=20),
        ),
    ]
