# Generated by Django 4.2.11 on 2026-05-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuideRequest',
        ),
    ]
