# Generated by Django 4.2.11 on 2026-05-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_delete_guiderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutguide',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
