# Generated by Django 4.2.11 on 2026-05-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_workoutguide_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pending_renewal_plan',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, null=True),
        ),
    ]
