# Generated by Django 4.2.11 on 2026-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_member_pending_renewal_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('visit_date', models.DateField(db_index=True)),
                ('amount_paid', models.FloatField(default=15.0)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='pending_renewal_plan',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, null=True),
        ),
    ]
