# Generated by Django 4.2.11 on 2026-05-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_guestvisit_alter_member_membership_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestvisit',
            name='guest_type',
            field=models.CharField(choices=[('student', 'Student'), ('regular', 'Regular')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='member_tier',
            field=models.CharField(choices=[('student', 'Student'), ('regular', 'Regular')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestvisit',
            name='amount_paid',
            field=models.FloatField(default=100.0),
        ),
    ]
