# Generated by Django 6.0.5 on 2026-05-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_guestvisit_guest_type_member_member_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='consecutive_rejections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='last_rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
