# Generated by Django 4.2.11 on 2026-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
