# Generated by Django 4.2.11 on 2026-06-05 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_workout_muscle_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('set_type', models.CharField(choices=[('warmup', 'Warm-up'), ('working', 'Working'), ('drop', 'Drop Set')], default='working', max_length=15)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_list', to='tracker.workout')),
            ],
        ),
    ]
