# Generated by Django 4.2.11 on 2026-06-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_workoutset'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='is_pr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='trainer_notes',
            field=models.TextField(blank=True),
        ),
    ]
